version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt  # Install dependencies

  build:
    commands:
      - python -m airflow dags list  # Command to check if DAGs are valid

artifacts:
  files:
    - dags/*.py  # Specify only DAG files
