version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Specify your desired Python version
    commands:
      - apt-get update
      - apt-get install -y cmake
      - pip install -r requirements.txt

  build:
    commands:
      - python -m airflow dags list  # Command to check if DAGs are valid

artifacts:
  files:
    - dags/*.py  # Specify only DAG files
